---
- name: Velero Install
  hosts: all
  gather_facts: false
  environment:
    KUBECONFIG: "{{ openshift_kubeconfig_file }}"
  roles:
    - role: gepaplexx.velero

- name: Restore
  hosts: all
  gather_facts: false
  environment:
    KUBECONFIG: "{{ openshift_kubeconfig_file }}"
  tasks:
    - name: Initiate Restore
      ansible.builtin.command:
        cmd: |
          velero create restore \
            --from-schedule backup \
            --allow-partially-failed false \
            --include-namespaces couchbase-hogarama \
            --wait
      changed_when: true

...
